CREATE TABLE robot_equipment (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    robot_id BIGINT NOT NULL,
    slot_name VARCHAR(32) NOT NULL,
    template_id VARCHAR(64) NOT NULL,
    name VARCHAR(128) NOT NULL,
    item_type VARCHAR(32) NOT NULL,
    quality VARCHAR(32) NOT NULL,
    required_level INT NOT NULL,
    attack_bonus INT NOT NULL,
    defense_bonus INT NOT NULL,
    hp_bonus INT NOT NULL,
    mp_bonus INT NOT NULL,
    crit_bonus DECIMAL(10, 6) NOT NULL,
    sell_price INT NOT NULL,
    enhancement_level INT NOT NULL DEFAULT 0,
    enhancement_luck INT NOT NULL DEFAULT 0,
    origin VARCHAR(160) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_robot_equipment_slot (robot_id, slot_name),
    KEY idx_robot_equipment_template (template_id),
    CONSTRAINT fk_robot_equipment_robot FOREIGN KEY (robot_id) REFERENCES robot_profile (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
