spring:
  application:
    name: mythic-realm

  datasource:
    url: jdbc:mysql://127.0.0.1:3307/mythicrealm?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: false
    clean-disabled: false
    locations: classpath:db/migration

  redis:
    host: localhost
    port: 6379
    database: 0

  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

server:
  port: 8080

logging:
  level:
    com.mythicrealm: DEBUG

mythic:
  database:
    destructive-reset-on-migration-error: true
  config:
    version: v1.1-level90-bloodmoon
